# Generated by Django 6.0 on 2025-12-16 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='created_at',
            new_name='pub_date',
        ),
    ]
